[package]
name = "carver-sdk"
description = "Portable application SDK for Carver libraries"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
carver-config = { path = "../carver-config", version = "0.1.0" }
carver-domain = { path = "../carver-domain", version = "0.1.0" }
carver-storage-sqlite = { path = "../carver-storage-sqlite", version = "0.1.0" }
async-channel.workspace = true
thiserror.workspace = true
time.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
