import type { ImageMetadata } from 'astro';

import agentDark from '../assets/screenshots/agent-dark.png';
import agentLight from '../assets/screenshots/agent-light.png';
import basesDark from '../assets/screenshots/bases-dark.png';
import basesLight from '../assets/screenshots/bases-light.png';
import editorDark from '../assets/screenshots/editor-dark.png';
import editorLight from '../assets/screenshots/editor-light.png';
import libraryDark from '../assets/screenshots/library-dark.png';
import libraryLight from '../assets/screenshots/library-light.png';
import settingsDark from '../assets/screenshots/settings-dark.png';
import settingsLight from '../assets/screenshots/settings-light.png';
import sourceDark from '../assets/screenshots/source-dark.png';
import sourceLight from '../assets/screenshots/source-light.png';

/** A single captured application view, paired across both UI themes. */
export interface Shot {
  alt: string;
  /** Optional caption; omit when the surrounding copy already describes it. */
  caption?: string;
  light: ImageMetadata;
  dark: ImageMetadata;
}

/**
 * Every application view the site presents, keyed by feature area.
 *
 * These are generated by `scripts/capture-screenshots.sh`, which drives the app
 * under headless Weston and writes the light/dark pairs here. A view only
 * renders once both variants exist, so a feature panel never shows an empty
 * slot while a capture is still pending.
 */
export type ShotName = 'editor' | 'source' | 'bases' | 'agent' | 'library' | 'settings';

export const shots: Partial<Record<ShotName, Shot>> = {
  editor: {
    alt: "Editing a note in Carver's rich text editor",
    light: editorLight,
    dark: editorDark,
  },
  source: {
    alt: 'Editing Carve source beside its live preview',
    light: sourceLight,
    dark: sourceDark,
  },
  bases: {
    alt: 'A saved Base with frontmatter columns and filters',
    light: basesLight,
    dark: basesDark,
  },
  agent: {
    alt: "Carver's connect-an-agent setup screen",
    light: agentLight,
    dark: agentDark,
  },
  library: {
    alt: 'Categories, recent notes, and the recoverable Trash',
    light: libraryLight,
    dark: libraryDark,
  },
  settings: {
    alt: "Carver's preferences",
    light: settingsLight,
    dark: settingsDark,
  },
};
