import type { ImageMetadata } from 'astro';

import agentDark from '../assets/screenshots/agent-dark.png';
import agentLight from '../assets/screenshots/agent-light.png';
import baseConfigDark from '../assets/screenshots/base-config-dark.png';
import baseConfigLight from '../assets/screenshots/base-config-light.png';
import baseListDark from '../assets/screenshots/base-list-dark.png';
import baseListLight from '../assets/screenshots/base-list-light.png';
import basesDark from '../assets/screenshots/bases-dark.png';
import basesLight from '../assets/screenshots/bases-light.png';
import editorDark from '../assets/screenshots/editor-dark.png';
import editorLight from '../assets/screenshots/editor-light.png';
import focusDark from '../assets/screenshots/focus-dark.png';
import focusLight from '../assets/screenshots/focus-light.png';
import libraryDark from '../assets/screenshots/library-dark.png';
import libraryLight from '../assets/screenshots/library-light.png';
import mediaDark from '../assets/screenshots/media-dark.png';
import mediaLight from '../assets/screenshots/media-light.png';
import searchDark from '../assets/screenshots/search-dark.png';
import searchLight from '../assets/screenshots/search-light.png';
import settingsDark from '../assets/screenshots/settings-dark.png';
import settingsLight from '../assets/screenshots/settings-light.png';
import sourceDark from '../assets/screenshots/source-dark.png';
import sourceLight from '../assets/screenshots/source-light.png';

/** A single captured application view, paired across both UI themes. */
export interface Shot {
  alt: string;
  /** Optional caption; omit when the surrounding copy already describes it. */
  caption?: string;
  light: ImageMetadata;
  dark: ImageMetadata;
}

/**
 * Every application view the site presents, keyed by feature area.
 *
 * These are generated by `scripts/capture-screenshots.sh`, which drives the app
 * under headless Weston and writes the light/dark pairs here. A view only
 * renders once both variants exist, so a feature panel never shows an empty
 * slot while a capture is still pending.
 */
export type ShotName =
  'editor' | 'media' | 'focus' | 'source' | 'bases' | 'agent' | 'library' | 'search' | 'settings';

export const shots: Partial<Record<ShotName, Shot>> = {
  editor: {
    alt: "Editing a note in Carver's rich text editor",
    light: editorLight,
    dark: editorDark,
  },
  media: {
    alt: "A note's images and attachments in the document sidebar",
    light: mediaLight,
    dark: mediaDark,
  },
  focus: {
    alt: 'A distraction-free writing view with no toolbar or sidebar',
    light: focusLight,
    dark: focusDark,
  },
  source: {
    alt: 'Editing Carve source beside its live preview',
    light: sourceLight,
    dark: sourceDark,
  },
  bases: {
    alt: 'A saved Base with frontmatter columns and filters',
    light: basesLight,
    dark: basesDark,
  },
  agent: {
    alt: "Carver's connect-an-agent setup screen",
    light: agentLight,
    dark: agentDark,
  },
  library: {
    alt: 'Categories, recent notes, and the recoverable Trash',
    light: libraryLight,
    dark: libraryDark,
  },
  search: {
    alt: 'Searching the library and filtering the note list',
    light: searchLight,
    dark: searchDark,
  },
  settings: {
    alt: "Carver's preferences",
    light: settingsLight,
    dark: settingsDark,
  },
};

/** One labelled slide in the Properties & Bases carousel. */
export interface BaseViewSlide {
  label: string;
  shot: Shot;
}

/**
 * The Base workflow shown in the Properties & Bases section: build a saved
 * view, choose how it presents notes, then switch between the grid and list.
 */
export const baseViewSlides: BaseViewSlide[] = [
  {
    label: 'A saved Base built from your frontmatter properties',
    shot: {
      alt: 'A saved Base with text, boolean, and date columns',
      light: basesLight,
      dark: basesDark,
    },
  },
  {
    label: 'Switch to a notes list to browse the same rows as cards',
    shot: {
      alt: 'A Base shown as a scrollable list of note cards',
      light: baseListLight,
      dark: baseListDark,
    },
  },
  {
    label: 'Choose columns, filters, sort rules, and how notes are shown',
    shot: {
      alt: "A Base's configuration form with its visible fields and view options",
      light: baseConfigLight,
      dark: baseConfigDark,
    },
  },
];
