[package]
name = "carver-gtk"
description = "Native GTK4 and Libadwaita frontend for Carver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cssparser.workspace = true
atomic-write-file.workspace = true
carver-config = { path = "../../crates/carver-config", version = "0.2.2" }
carver-agent-integration = { path = "../../crates/carver-agent-integration", version = "0.2.2" }
carver-domain = { path = "../../crates/carver-domain", version = "0.2.2" }
carver-sdk = { path = "../../crates/carver-sdk", version = "0.2.2" }
carver-storage-sqlite = { path = "../../crates/carver-storage-sqlite", version = "0.2.2" }
carver-editor-protocol = { path = "../../crates/carver-editor-protocol", version = "0.2.2" }
carver-export = { path = "../../crates/carver-export", version = "0.2.2" }
base64.workspace = true
carve-lang.workspace = true
futures-util = { version = "0.3", default-features = false, features = ["std"] }
glib.workspace = true
gdk-pixbuf.workspace = true
gtk.workspace = true
libadwaita.workspace = true
time.workspace = true
uuid.workspace = true
serde_json.workspace = true
sourceview5.workspace = true
thiserror.workspace = true
tempfile.workspace = true
webkit6 = "0.6.1"
lol_html.workspace = true
html-escape.workspace = true

[dev-dependencies]
zip.workspace = true

[build-dependencies]
glib-build-tools = "0.22"

[lints]
workspace = true
