[package]
name = "carver-gtk"
description = "Native GTK4 and Libadwaita frontend for Carver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
carver-config = { path = "../../crates/carver-config" }
carver-sdk = { path = "../../crates/carver-sdk" }
carver-richtext = { path = "../../crates/carver-richtext" }
glib.workspace = true
gtk.workspace = true
libadwaita.workspace = true
time.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
